from __future__ import annotations

"""Implementation agent codegen — writes a real URL shortener project from a design spec."""

from pathlib import Path
from typing import Any


def generate_url_shortener(project_dir: Path, spec: dict[str, Any]) -> list[str]:
    """Generate a runnable FastAPI URL shortener into project_dir. Returns relative file paths."""
    project_dir.mkdir(parents=True, exist_ok=True)
    features = spec.get("features", {})
    app_name = spec.get("app_name", "Generated URL Shortener")

    files: dict[str, str] = {
        "requirements.txt": _requirements(),
        "README.md": _readme(app_name, features, spec),
        "app/__init__.py": '"""Generated URL shortener application."""\n',
        "app/database.py": _database(),
        "app/models.py": _models(features),
        "app/schemas.py": _schemas(features),
        "app/services.py": _services(features),
        "app/main.py": _main(app_name, features),
        "tests/__init__.py": "",
        "tests/test_app.py": _tests(features),
        "tests/test_edge_cases.py": _edge_tests(features),
    }

    written: list[str] = []
    for rel, content in files.items():
        path = project_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(rel)
    return written


def _requirements() -> str:
    return "\n".join(
        [
            "fastapi>=0.115.0",
            "uvicorn[standard]>=0.30.0",
            "sqlalchemy>=2.0.30",
            "pydantic>=2.8.0",
            "httpx>=0.27.0",
            "pytest>=8.2.0",
            "",
        ]
    )


def _readme(app_name: str, features: dict[str, Any], spec: dict[str, Any]) -> str:
    return f"""# {app_name}

Auto-generated by the **Agentic SDLC Builder** from this requirement:

> {spec.get('normalized_requirement', '')}

## Features enabled
{chr(10).join(f'- {k}: {v}' for k, v in features.items())}

## Run
```bash
pip install -r requirements.txt
uvicorn app.main:app --reload --port 8000
```

## Test
```bash
pytest -q
```

## API
- `POST /api/v1/urls` — create short URL
- `GET /{{code}}` — redirect
- `GET /api/v1/urls/{{code}}` — metadata
- `GET /api/v1/urls/{{code}}/analytics` — click analytics
- `GET /health` — health check
"""


def _database() -> str:
    return '''from __future__ import annotations

from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

DB_PATH = Path(__file__).resolve().parents[1] / "data" / "shortener.db"
DB_PATH.parent.mkdir(parents=True, exist_ok=True)
DATABASE_URL = f"sqlite:///{DB_PATH}"

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    from app import models  # noqa: F401

    Base.metadata.create_all(bind=engine)
'''


def _models(features: dict[str, Any]) -> str:
    alias_field = ""
    rate_field = ""
    if features.get("custom_alias"):
        alias_field = '    custom_alias: Mapped[str | None] = mapped_column(String(64), unique=True, nullable=True)\n'
    if features.get("rate_limit"):
        rate_field = "    rate_limit_per_minute: Mapped[int] = mapped_column(Integer, default=60)\n"

    return f'''from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class ShortURL(Base):
    __tablename__ = "short_urls"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    code: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    long_url: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    click_count: Mapped[int] = mapped_column(Integer, default=0)
    is_active: Mapped[bool] = mapped_column(default=True)
{alias_field}{rate_field}

class ClickEvent(Base):
    __tablename__ = "click_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    code: Mapped[str] = mapped_column(String(32), index=True)
    clicked_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    user_agent: Mapped[str | None] = mapped_column(String(512), nullable=True)
'''


def _schemas(features: dict[str, Any]) -> str:
    alias = ""
    rate = ""
    resp_extra = ""
    if features.get("custom_alias"):
        alias = '    custom_alias: str | None = Field(default=None, min_length=3, max_length=32)\n'
        resp_extra += "    custom_alias: str | None = None\n"
    if features.get("rate_limit"):
        rate = "    rate_limit_per_minute: int = Field(default=60, ge=1, le=1000)\n"
        resp_extra += "    rate_limit_per_minute: int = 60\n"

    return f'''from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, HttpUrl


class URLCreate(BaseModel):
    url: HttpUrl
{alias}{rate}

class URLResponse(BaseModel):
    code: str
    short_url: str
    long_url: str
    created_at: datetime
    click_count: int
{resp_extra}
    model_config = {{"from_attributes": True}}


class AnalyticsResponse(BaseModel):
    code: str
    long_url: str
    click_count: int
    recent_clicks: list[dict]


class HealthResponse(BaseModel):
    status: str
    service: str
'''


def _services(features: dict[str, Any]) -> str:
    has_alias = bool(features.get("custom_alias"))
    has_rate = bool(features.get("rate_limit"))

    create_sig = "db: Session, long_url: str, custom_alias: str | None = None, rate_limit_per_minute: int = 60"
    if has_alias:
        allocate_block = '''
    code = custom_alias
    if code:
        if not ALIAS_RE.match(code):
            raise HTTPException(status_code=400, detail="Invalid custom alias")
        if db.query(ShortURL).filter((ShortURL.code == code) | (ShortURL.custom_alias == code)).first():
            raise HTTPException(status_code=409, detail="Alias already in use")
    else:
        code = None
        for _ in range(8):
            candidate = generate_code()
            if not db.query(ShortURL).filter(ShortURL.code == candidate).first():
                code = candidate
                break
        if not code:
            raise HTTPException(status_code=500, detail="Unable to allocate short code")
'''
    else:
        allocate_block = '''
    code = None
    for _ in range(8):
        candidate = generate_code()
        if not db.query(ShortURL).filter(ShortURL.code == candidate).first():
            code = candidate
            break
    if not code:
        raise HTTPException(status_code=500, detail="Unable to allocate short code")
'''

    rate_arg = "rate_limit_per_minute=rate_limit_per_minute," if has_rate else ""
    alias_arg = "custom_alias=custom_alias," if has_alias else ""

    return f'''from __future__ import annotations

import re
import secrets
import string
from urllib.parse import urlparse

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.models import ClickEvent, ShortURL

CODE_ALPHABET = string.ascii_letters + string.digits
ALIAS_RE = re.compile(r"^[A-Za-z0-9_-]{{3,32}}$")
BLOCKED_HOSTS = {{"localhost", "127.0.0.1", "0.0.0.0"}}


def generate_code(length: int = 7) -> str:
    return "".join(secrets.choice(CODE_ALPHABET) for _ in range(length))


def validate_target_url(url: str) -> None:
    parsed = urlparse(url)
    if parsed.scheme not in {{"http", "https"}}:
        raise HTTPException(status_code=400, detail="Only http/https URLs are allowed")
    host = (parsed.hostname or "").lower()
    if host in BLOCKED_HOSTS:
        raise HTTPException(status_code=400, detail="Local/private targets are not allowed")


def create_short_url({create_sig}) -> ShortURL:
    validate_target_url(long_url)
{allocate_block}
    row = ShortURL(
        code=code,
        long_url=long_url,
        {alias_arg}
        {rate_arg}
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def resolve_and_track(db: Session, code: str, user_agent: str | None = None) -> ShortURL:
    row = db.query(ShortURL).filter(ShortURL.code == code, ShortURL.is_active.is_(True)).first()
    if not row:
        raise HTTPException(status_code=404, detail="Short URL not found")
    row.click_count += 1
    db.add(ClickEvent(code=code, user_agent=(user_agent or "")[:512] or None))
    db.commit()
    db.refresh(row)
    return row


def get_metadata(db: Session, code: str) -> ShortURL:
    row = db.query(ShortURL).filter(ShortURL.code == code).first()
    if not row:
        raise HTTPException(status_code=404, detail="Short URL not found")
    return row


def get_analytics(db: Session, code: str, limit: int = 10) -> dict:
    row = get_metadata(db, code)
    events = (
        db.query(ClickEvent)
        .filter(ClickEvent.code == code)
        .order_by(ClickEvent.clicked_at.desc())
        .limit(limit)
        .all()
    )
    return {{
        "code": row.code,
        "long_url": row.long_url,
        "click_count": row.click_count,
        "recent_clicks": [
            {{"clicked_at": e.clicked_at.isoformat(), "user_agent": e.user_agent}} for e in events
        ],
    }}
'''


def _main(app_name: str, features: dict[str, Any]) -> str:
    has_alias = bool(features.get("custom_alias"))
    has_rate = bool(features.get("rate_limit"))

    create_args = ["db", "long_url=str(payload.url)"]
    if has_alias:
        create_args.append("custom_alias=payload.custom_alias")
    if has_rate:
        create_args.append("rate_limit_per_minute=payload.rate_limit_per_minute")
    create_call = ",\n        ".join(create_args)

    resp_extra = ""
    if has_alias:
        resp_extra += "\n        custom_alias=getattr(row, 'custom_alias', None),"
    if has_rate:
        resp_extra += "\n        rate_limit_per_minute=getattr(row, 'rate_limit_per_minute', 60),"

    return f'''from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI, Request
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session

from app import services
from app.database import get_db, init_db
from app.schemas import AnalyticsResponse, HealthResponse, URLCreate, URLResponse


@asynccontextmanager
async def lifespan(_: FastAPI):
    init_db()
    yield


app = FastAPI(title="{app_name}", version="1.0.0", lifespan=lifespan)


def to_response(row, request: Request) -> URLResponse:
    base = str(request.base_url).rstrip("/")
    return URLResponse(
        code=row.code,
        short_url=f"{{base}}/{{row.code}}",
        long_url=row.long_url,
        created_at=row.created_at,
        click_count=row.click_count,{resp_extra}
    )


@app.get("/health", response_model=HealthResponse)
def health():
    return HealthResponse(status="ok", service="url-shortener")


@app.post("/api/v1/urls", response_model=URLResponse, status_code=201)
def create_url(payload: URLCreate, request: Request, db: Session = Depends(get_db)):
    row = services.create_short_url(
        {create_call}
    )
    return to_response(row, request)


@app.get("/api/v1/urls/{{code}}", response_model=URLResponse)
def get_url(code: str, request: Request, db: Session = Depends(get_db)):
    return to_response(services.get_metadata(db, code), request)


@app.get("/api/v1/urls/{{code}}/analytics", response_model=AnalyticsResponse)
def analytics(code: str, db: Session = Depends(get_db)):
    return services.get_analytics(db, code)


@app.get("/{{code}}")
def redirect(code: str, request: Request, db: Session = Depends(get_db)):
    if code in {{"docs", "openapi.json", "redoc", "health", "api"}}:
        return {{"detail": "Not a short code"}}
    row = services.resolve_and_track(db, code, user_agent=request.headers.get("user-agent"))
    return RedirectResponse(url=row.long_url, status_code=307)
'''


def _tests(features: dict[str, Any]) -> str:
    alias_test = ""
    if features.get("custom_alias"):
        alias_test = '''

def test_custom_alias():
    res = client.post("/api/v1/urls", json={"url": "https://example.org/a", "custom_alias": "demoAlias"})
    assert res.status_code == 201
    assert res.json()["code"] == "demoAlias"
'''

    return f'''from __future__ import annotations

import sys
from pathlib import Path

from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.database import Base, engine, init_db
from app.main import app


def setup_module():
    Base.metadata.drop_all(bind=engine)
    init_db()


client = TestClient(app)


def test_health():
    assert client.get("/health").json()["status"] == "ok"


def test_create_redirect_analytics():
    create = client.post("/api/v1/urls", json={{"url": "https://example.com/long"}})
    assert create.status_code == 201
    code = create.json()["code"]
    redirect = client.get(f"/{{code}}", follow_redirects=False)
    assert redirect.status_code == 307
    assert redirect.headers["location"] == "https://example.com/long"
    analytics = client.get(f"/api/v1/urls/{{code}}/analytics")
    assert analytics.status_code == 200
    assert analytics.json()["click_count"] >= 1


def test_blocks_localhost():
    res = client.post("/api/v1/urls", json={{"url": "http://localhost/secret"}})
    assert res.status_code == 400
{alias_test}
'''


def _edge_tests(features: dict[str, Any]) -> str:
    """Extra tests for validation/analytics edge cases (correct status codes)."""
    alias_conflict = ""
    if features.get("custom_alias"):
        alias_conflict = '''

def test_custom_alias_conflict():
    first = client.post(
        "/api/v1/urls",
        json={"url": "https://example.org/one", "custom_alias": "sameAlias"},
    )
    assert first.status_code == 201
    second = client.post(
        "/api/v1/urls",
        json={"url": "https://example.org/two", "custom_alias": "sameAlias"},
    )
    assert second.status_code == 409
'''

    return f'''from __future__ import annotations

import sys
from pathlib import Path

from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.database import Base, engine, init_db
from app.main import app


def setup_module():
    Base.metadata.drop_all(bind=engine)
    init_db()


client = TestClient(app)


def test_invalid_url_rejected_by_schema():
    """Pydantic HttpUrl rejects malformed URLs with 422 (not 400)."""
    response = client.post("/api/v1/urls", json={{"url": "invalid-url"}})
    assert response.status_code == 422


def test_missing_url_field():
    response = client.post("/api/v1/urls", json={{}})
    assert response.status_code == 422


def test_analytics_unknown_code():
    response = client.get("/api/v1/urls/doesnotexist/analytics")
    assert response.status_code == 404


def test_redirect_unknown_code():
    response = client.get("/missingcode", follow_redirects=False)
    assert response.status_code == 404


def test_analytics_increments_after_multiple_clicks():
    create = client.post("/api/v1/urls", json={{"url": "https://example.com/clicks"}})
    assert create.status_code == 201
    code = create.json()["code"]
    client.get(f"/{{code}}", follow_redirects=False)
    client.get(f"/{{code}}", follow_redirects=False)
    analytics = client.get(f"/api/v1/urls/{{code}}/analytics")
    assert analytics.status_code == 200
    assert analytics.json()["click_count"] >= 2
{alias_conflict}
'''